#!/usr/bin/env python3
"""Generate TEST_VECTORS.md from the committed vectors, statement and manifest (deterministic)."""
import hashlib, json, glob, os

def sha(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()

pos = "vectors/p1.instance.json"
negs = {
 "n1_determined": ("N1", "evidence f0s0 determines `secondBit`; no pair can be a target", "tests/DeterminedReject.lean; must_fail/N1_determined"),
 "n2_incompatible": ("N2", "w10 not Compatible with f0s_ though values differ (w01=1, w10=0)", "tests/IncompatibleWitnessReject.lean; must_fail/N2_incompatible_witness"),
 "n3_same_value": ("N3", "both witnesses Compatible and distinct; `firstBit` has equal value", "tests/SameValueReject.lean; must_fail/N3_same_value"),
 "n4_empty_compatible": ("N4", "evidence `inconsistent`: no compatible world; neither Underdetermined nor Determinate", "tests/NoWitnessDoesNotImplyDeterminate.lean; must_fail/N4_no_witness_empty_compatible"),
 "m3_outside_world": ("M3", "wOut compatible and divergent but not in Wπ", "tests/IncompatibleWitnessReject.lean; must_fail/M3_witness_outside_W"),
 "m_outside_evidence": ("M-E", "evidence `outside` not in Eπ", "tests/IncompatibleWitnessReject.lean; must_fail/M_evidence_outside_E"),
 "m8_whitespace": ("M8", "space after a colon (non-canonical)", "tests/Decoder.lean"),
 "m8_key_order": ("M8", "keys not in sorted order", "tests/Decoder.lean"),
 "m8_trailing_newline": ("M8", "trailing LF", "tests/Decoder.lean"),
 "m8_unknown_token": ("M8", "unknown world token w02", "tests/Decoder.lean"),
 "m8_escape": ("M8", "JSON escape \\u0042 in a token", "tests/Decoder.lean"),
 "m32_wrong_spec": ("M32/N8", "spec digest field differs from the profile digest", "tests/Decoder.lean; must_fail/N8_changed_profile_identity"),
 "m_wrong_kind": ("—", "wrong wire kind identifier", "tests/Decoder.lean"),
 "m_wrong_profile": ("—", "wrong profile identifier", "tests/Decoder.lean"),
}
st = json.loads(open("vectors/out/p1.statement.json").read())
L = []
L.append("# Test vectors (generated by `scripts/gen_testvectors_md.py`; do not edit by hand)\n")
L.append("Status: DRAFT, self-reviewed, not independently validated. Signature: public deterministic **TEST key**; SCITT registration **NOT DEMONSTRATED**.\n")
L.append("## Wire format\n")
L.append('`{"claim":C,"evidence":E,"kind":"p10-s1-instance-v0","profile":"p10-s1-toy-v0","spec":"sha256:<profile digest>","w0":A,"w1":B}` — a strict subset of RFC 8785 JCS (sorted ASCII keys, no whitespace, no trailing newline, values over `[A-Za-z0-9_.:-]`). Tokens — claim: `secondBit|firstBit`; evidence: `f{0,1}s{_,0,1}|inconsistent|outside`; world: `w00|w01|w10|w11|wOut`.\n')
L.append("## Positive vector P1\n")
L.append(f"| file | SHA-256 | outcome |\n|---|---|---|\n| `{pos}` | `{sha(pos)}` | certificate PASS (`P10.Certs.P1.cert`) |\n")
L.append("Bytes: `" + open(pos).read() + "`\n")
L.append("## Negative vectors (all rejected)\n")
L.append("For the semantic negatives (N1–N4, M3, M-E) the kernel proves `¬ Holds bytes` at the PROPOSITION level (the exact `CertificateTargetV0` for the witnesses named in the bytes is refuted), and the F1 must-fail tests show that an honest `Underdetermined` proof through a *different* pair no longer type-checks.\n")
L.append("| id | file | SHA-256 | why rejected | Lean evidence |\n|---|---|---|---|---|")
for k, (i, why, ev) in negs.items():
    p = f"vectors/negative/{k}.json"
    L.append(f"| {i} | `{p}` | `{sha(p)[:16]}…` | {why} | {ev} |")
L.append("")
L.append("## Signed statement (in-toto Statement v1 in COSE_Sign1)\n")
L.append("| artifact | SHA-256 |\n|---|---|")
for p in ("vectors/out/p1.statement.json", "vectors/out/p1.cose", "manifest/VerifierManifestS1.json"):
    L.append(f"| `{p}` | `{sha(p)}` |")
L.append("")
pred = st["predicate"]
L.append("Bound fields (all recomputed and matched by `scripts/p10tool.py verify`):\n")
L.append("| binding | value |\n|---|---|")
rows = [
 ("normative profile digest", pred["profile"]["spec_sha256"]),
 ("profile source commit", pred["profile"]["source_commit"]),
 ("instance digest (= in-toto subject digest, kernel-checked)", pred["instance"]["sha256"]),
 ("claim digest (JCS `{\"claim\":…}`)", pred["claim"]["digest"]),
 ("evidence digest (JCS `{\"evidence\":…}`)", pred["evidence"]["digest"]),
 ("witness w0 digest (JCS `{\"world\":…}`)", pred["witnesses"][0]["digest"]),
 ("witness w1 digest", pred["witnesses"][1]["digest"]),
 ("proposition (Lean statement)", "`" + pred["proposition"]["lean_statement"] + "`"),
 ("proposition identity digest", pred["proposition"]["identity_digest"]),
 ("semantics source digest (Core, Certificate, Fixtures)", pred["verifier"]["semantics_source_digest"]),
 ("decoder/canonicalizer/binding source digest (Bytes, Wire, Sha256, Bound)", pred["verifier"]["decoder_source_digest"]),
 ("certificate module digest", pred["certificate"]["lean_module_sha256"]),
 ("axiom-audit output digest", pred["certificate"]["axiom_audit_output_sha256"]),
 ("checker-owned check output digest", pred["certificate"]["checker_owned_output_sha256"]),
 ("Lean version", pred["verifier"]["lean_version_string"]),
 ("Lean executable digest", pred["verifier"]["lean_executable_sha256"]),
 ("libleanshared.so digest", pred["verifier"]["lean_shared_library_sha256"]),
 ("Mathlib", pred["verifier"]["mathlib"]),
 ("lake-manifest.json digest", pred["verifier"]["lake_manifest_sha256"]),
 ("verifier manifest digest (pinned in `profile/VERIFIER_MANIFEST_PIN.txt`)", pred["verifier"]["manifest_sha256"]),
 ("verifier scripts digest", pred["verifier"]["verifier_scripts_digest"]),
 ("limitations digest", pred["limitations_digest"]),
 ("proof/check mode", pred["certificate"]["proof_mode"]),
]
for a, b in rows:
    L.append(f"| {a} | {b if b.startswith('`') else '`'+b+'`'} |")
L.append("")
L.append("Predicate type (experimental, unregistered): `" + st["predicateType"] + "`. `limitations` is a must-understand field (verifier rejects a predicate without it); it carries the profile's AP1 and coverage/instance texts **verbatim** (extracted from the snapshot and compared byte-for-byte) plus S1-specific limitations.\n")
L.append("COSE: tag 18; protected `{1:-8 (EdDSA), 3:\"application/vnd.in-toto+json\", 4:kid, 15:{1:iss, 2:sub}}`, empty unprotected header (no label 394 Receipt). Checked by pycose (`p10tool.py`) and, independently, by `scripts/cose_crosscheck.py` (RFC 9052 Sig_structure with `cryptography` only).\n")
L.append("## What is real and what is not\n")
L.append("* REAL, kernel-checked: `P10.Certs.P1.cert`, the reject theorems, decoder/round-trip theorems, SHA-256 FIPS vectors.\n* REAL, script-checked: profile digest, source/manifest digests, JCS form and digests of the statement, COSE signature (test key).\n* NOT DEMONSTRATED: SCITT registration/receipt, any Transparency Service, InstanceCommitment/closure/coverage, independent validation.\n")
L.append("## Mutation suite\n")
L.append("`python3 scripts/mutation_suite.py` — each case mutates a scratch copy and asserts the expected fail-closed verdict *and reason*. See the script's `CASES` table (statement-, source-, instance-, toolchain-, certificate- and runtime-level mutations, plus the pinned/unpinned `INFO` pair) and `THREAT_MODEL.md`.\n")
L.append("## Benchmarks (build environment: 4 vCPU, 15 GB, Lean 4.33.0)\n")
L.append("| what | measured |\n|---|---|\n| clean `lake build`, all modules (includes kernel decode + 4-block SHA-256 of P1) | ≈ 19 s, peak RSS ≈ 2.4 GB |\n| `tests/Sha256Vectors.lean` (5 blocks) | ≈ 11 s |\n| `tests/Decoder.lean` (14 vectors) | ≈ 2.5 s |\n| checker-owned check of the P1 certificate | ≈ 1.2 s |\n| canonical `verify.sh` without mutation suite | ≈ 1.5 min |\n| ordinary `decide` on the 196-byte decode + canonical check | ≈ 1–2 s |\n")
L.append("Design findings: (1) Lean 4.33 `String.toList` reduces slowly and pulls `propext`/`Classical.choice`, so bytes are `List Nat`; (2) `Nat.land/lor/xor` depend on `propext`, so SHA-256 bit operations are rebuilt from `/ % + *` (`Nat.rec`, direct `Nat.*` calls: ≈4× faster than instance-based operators); (3) wildcard patterns over enumeration types compile through `propext`-dependent lemmas, so matches list all constructors; (4) universal `decode ∘ encode = id` by brute-force `decide` over 175 instances timed out, so it is proved structurally. `native_decide` was never needed.\n")
open("TEST_VECTORS.md", "w", encoding="utf-8").write("\n".join(L))
